version: "3"
services:
  database:
    image: mysql:5.7
    platform: linux/x86_64
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: happytree-db
    environment:
      MYSQL_DATABASE: happytree_db
      MYSQL_ROOT_PASSWORD: happytree
      MYSQL_USER: sujee
      MYSQL_PASSWORD : happytree
    ports:
      - 3306:3306


  springbootapp:
    build: .
    container_name: happytree-backend

    command:
      - bash
        - -c
        - |
        ./wait-for-it.sh happytree-db:3306 -s -t 100
        java -jar /app.jar

    ports:
      - 4000:8080
    depends_on:
      - database